GameStore/GameStore/Areas/Admin/Controllers/GameController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using GameStore.Authorization.Infrastructure;
using GameStore.Controllers;
using GameStore.Extensions.Enums;
using GameStore.Services.DTO;
using GameStore.Services.Interfaces;
using GameStore.ViewModels.Models;
using GameStore.ViewModels.ViewModels.Game;
using GameStore.ViewModels.ViewModels.Genre;
using GameStore.ViewModels.ViewModels.PlatformType;
using GameStore.ViewModels.ViewModels.Publisher;

namespace GameStore.Areas.Admin.Controllers
{
    [Authorize(Roles = "Manager,Administrator")]
    public class GameController : BaseController
    {
        private readonly IMapper _mapper;
        private readonly IGameService _gameService;
        private readonly IGenreService _genreService;
        private readonly IPlatformTypeService _platformTypeService;
        private readonly IPublisherService _publisherService;
        private readonly IGameTranslation _gameTranslation;
        private readonly IFilterService _filterService;
        private readonly ILanguageService _languageService;
        private const string LangRus = "ru";
        private const string LangEn = "en";

        public GameController(IAuthentication authentication, IMapper mapper, IGameService gameService , IGenreService genreService , 
            IPlatformTypeService platformTypeService , IPublisherService publisherService , IGameTranslation gameTranslation , 
            IFilterService filterService, ILanguageService languageService) : base(authentication)
        {
            _mapper = mapper;
            _gameService = gameService;
            _genreService = genreService;
            _platformTypeService = platformTypeService;
            _publisherService = publisherService;
            _gameTranslation = gameTranslation;
            _filterService = filterService;
            _languageService = languageService;
        }

        [HttpGet]
        public ActionResult Index(ElementsPerPage? elementsPerPage, int page = 1)
        {
            var pagesSize = GetPagesSize(elementsPerPage);

            var gamesesModel = _mapper.Map<List<GameIndexViewModel>>(_filterService.Filter(new FilterDto (),
                    (page - 1) * pagesSize, pagesSize));

            var pageInfo = new PageInfo
            {
                PageNumber = page,
                PageSize = pagesSize,
                TotalItems = _filterService.GamesCount(new FilterDto ())
            };

            var model = new GamesListViewModel
            {
                SelectedElements = elementsPerPage,
                Games = gamesesModel,
                PageInfo = pageInfo
            };

            return View(model);
        }

        [HttpGet]
        public ActionResult Details(string key)
        {
            var gameByKey = _gameService.GetGameByKey(key);
            var game = _mapper.Map<GameDto, CreateGameViewModel>(gameByKey);

            var namesList = game.Publishers.Select(publisher => publisher.CompanyName).ToList();

            var model = new GamePublisherViewModel
            {
                Game = game,
                Names = namesList
            };

            return View(model);

        }

        [HttpGet]
        public ActionResult Update(string key)
        {
            var game = _mapper.Map<GameUpdateViewModel>(_gameService.GetGameByKey(key));

            var languageRus = _languageService.GetLanguageByName(LangRus);
            var languageEn = _languageService.GetLanguageByName(LangEn);
            game.Description = _gameTranslation.GetTranslation(game.Id, languageRus.Id)?.Description;
            game.DescriptionEnglish = _gameTranslation.GetTranslation(game.Id, languageEn.Id)?.Description;

            game.Genres = _mapper.Map<List<GenreViewModel>>(_genreService.GetAllGenres());
            game.PlatformTypes = _mapper.Map<List<PlatformTypeViewModel>>(_platformTypeService.GetAllPlatformTypes());
            game.Publishers = _mapper.Map<List<PublisherViewModel>>(_publisherService.GetAllPublishers());

            return View(game);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(GameUpdateViewModel game)
        {
            ActionResult result;

            if (ModelState.IsValid)
            {
                if (game.File != null)
                {
                    var pic = Path.GetFileName(game.File.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/File"), pic);
                    game.File.SaveAs(path);
                    game.Picture = "/Content/File/" + pic;
                }

                var gameDto = _mapper.Map<GameDto>(game);
                _gameService.Update(gameDto);
                result = RedirectToAction("Index");
            }
            else
            {
                result = RedirectToAction("Update", new { key = game.Key });
            }

            return result;
        }

        [HttpGet]
        public ActionResult New()
        {
            var model = new CreateGameViewModel
            {
                Genres = _genreService.GetAllGenres().ToList(),
                PlatformTypes = _platformTypeService.GetAllPlatformTypes().ToList(),
                Publishers = _publisherService.GetAllPublishers().ToList()
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult New(CreateGameViewModel game)
        {
            ActionResult result;

            if (ModelState.IsValid)
            {
                if (game.File != null)
                {
                    var pic = Path.GetFileName(game.File.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/File"), pic);
                    game.File.SaveAs(path);
                    game.Picture = "/Content/File/" + pic;
                }

                var gameDto = _mapper.Map<GameDto>(game);
                _gameService.Create(gameDto);
                result = RedirectToAction("Index");
            }
            else
            {
                result = RedirectToAction("New");
            }

            return result;
        }

        [HttpGet]
        public ActionResult Remove(string key)
        {
            _gameService.Delete(key);
            return Content("The game has been removed");
        }

        private int GetPagesSize(ElementsPerPage? elementsPerPage)
        {
            int pagesSize;

            if (elementsPerPage == ElementsPerPage.All)
            {
                pagesSize = _filterService.GamesCount(new FilterDto());
            }
            else
            {
                pagesSize = elementsPerPage != null ? (int)elementsPerPage : (int)ElementsPerPage.Three;
            }
            return pagesSize;
        }
    }
}

GameStore/GameStore/Areas/Admin/Controllers/RoleController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using GameStore.Authorization.Infrastructure;
using GameStore.Controllers;
using GameStore.Services.DTO;
using GameStore.Services.Interfaces;
using GameStore.ViewModels.ViewModels.Role;

namespace GameStore.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class RoleController : BaseController
    {
        private readonly IMapper _mapper;
        private readonly IRoleService _roleService;

        public RoleController(IAuthentication authentication, IMapper mapper, IRoleService roleService) : base(authentication)
        {
            _mapper = mapper;
            _roleService = roleService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var model = new RolesListViewModel {Roles = _mapper.Map<List<RoleViewModel>>(_roleService.GetAll())};
            return View(model);
        }


        [HttpGet]
        public ActionResult Create()
        {
            var model = new RoleViewModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var roleDto = _mapper.Map<RoleDTo>(model);
                _roleService.Create(roleDto);
                return RedirectToAction("Index");
            }

            return View("Create", model);
        }

        public ActionResult Delete(string name)
        {
            _roleService.Delete(name);
            return RedirectToAction("Index");
        }
    }
}

GameStore/GameStore/Controllers/CommentController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using GameStore.Authorization.Infrastructure;
using GameStore.Services.DTO;
using GameStore.Services.Interfaces;
using GameStore.ViewModels.ViewModels.Comment;

namespace GameStore.Controllers
{
    [AllowAnonymous]
    public class CommentController : BaseController
    {
        private readonly ICommentService _commentService;
        private readonly IGameService _gameService;
        private readonly IMapper _mapper;

        public CommentController(ICommentService commentService, IMapper mapper, IGameService gameService , IAuthentication authentication) : base(authentication)
        {
            _commentService = commentService;
            _mapper = mapper;
            _gameService = gameService;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewComment(CommentFormViewModel model)
        {
            ActionResult result;

            if (ModelState.IsValid)
            {
                model.Comment.GameId = _gameService.GetGameByKey(model.GameKey).Id;
                var commentDto = _mapper.Map<CommentDto>(model.Comment);
                _commentService.Create(commentDto);
                result = RedirectToAction("Comments", new {model.GameKey});
            }
            else
            {
                result = RedirectToAction("Comments", new {model.GameKey});
            }

            return result;
        }

        [HttpGet]
        public ActionResult Comments(string key)
        {
            var allCommentsForGame = _commentService.GetAllCommentsForGame(key);
            var comments = _mapper.Map<IEnumerable<CommentDto>, List<CommentViewModel>>(allCommentsForGame);

            var model = new CommentFormViewModel
            {
                Comments = comments,
                GameKey = key 
            };

            return View(model);
        }
    }
}

GameStore/GameStore/Controllers/PublisherController.cs
using System.Web.Mvc;
using AutoMapper;
using GameStore.Authorization.Infrastructure;
using GameStore.Services.DTO;
using GameStore.Services.Interfaces;
using GameStore.ViewModels.ViewModels.Publisher;

namespace GameStore.Controllers
{
    [AllowAnonymous]
    public class PublisherController : BaseController
    {
        private readonly IMapper _mapper;
        private readonly IPublisherService _publisherService;

        public PublisherController(IMapper mapper, IPublisherService publisherService , IAuthentication authentication) : base(authentication)
        {
            _mapper = mapper;
            _publisherService = publisherService;
        }

        [HttpGet]
        public ActionResult Details(string companyName)
        {
            if (companyName == null)
            {
                return HttpNotFound();
            }
                
            var publisherByCompanyName = _publisherService.GetPublisherByCompanyName(companyName);
            var publisher = _mapper.Map<PublisherDto, PublisherViewModel>(publisherByCompanyName);
            return View(publisher);
        }
    }
}

GameStore/GameStore/Areas/Admin/Views/Shared/_Layout.cshtml
@using Resources
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <meta name="description" content="The description of my page" />
</head>
<body style="background-color: whitesmoke ">
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand" area ="">GameStore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav nav-pills pull-right">
                    @Html.Action("UserLogin", new { area = "", controller = "Account" })
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle linkcenter" type="button" data-toggle="dropdown">
                        @Resource.ChooseLang
                        <span class="caret"></span>
                    </button>
                    <ul id="localization" class="dropdown-menu">
                        <li id="en"><a class="lang-value" data-type="enLink" href="/en/">English</a></li>
                        <li id="ru"><a class="lang-value" data-type="enLink" href="/ru/">Русский</a></li>
                    </ul>
                </div>
            </div>
            <div id="wrapper">
                <div id="sidebar-wrapper">
                    <ul class="sidebar-nav nav-pills nav-stacked" id="menu">
                        <li>
                            <a href="@Url.Action("Index", "User")"><span class="fa-stack fa-lg pull-left"><i class="fa fa-cloud-download fa-stack-1x "></i></span>@Resources.Resource.Users</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Role")"> <span class="fa-stack fa-lg pull-left"><i class="fa fa-cart-plus fa-stack-1x "></i></span>@Resources.Resource.Roles</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Game")"><span class="fa-stack fa-lg pull-left"><i class="fa fa-youtube-play fa-stack-1x "></i></span>@Resources.Resource.Games</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Genre")"><span class="fa-stack fa-lg pull-left"><i class="fa fa-wrench fa-stack-1x "></i></span>@Resources.Resource.Genres</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Publisher")"><span class="fa-stack fa-lg pull-left"><i class="fa fa-server fa-stack-1x "></i></span>@Resources.Resource.Publishers</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Comment")"><span class="fa-stack fa-lg pull-left"><i class="fa fa-server fa-stack-1x "></i></span>@Resources.Resource.CommentsList</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Order")"><span class="fa-stack fa-lg pull-left"><i class="fa fa-server fa-stack-1x "></i></span>@Resources.Resource.Orders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                @RenderBody()
            </div>
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
        </div>
    </div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/customScripts")
@RenderSection("scripts", false)
</body>
</html>